---
- name: stop tablesnap systemd service
  systemd:
    name: tablesnap.service
    state: stopped
  ignore_errors: true

- name: install python2-pip
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "python2-pip"

- name: install virtualenv and packages
  command: "{{ item }}"
  with_items:
    - "pip2 install --upgrade pip"
    - "pip2 install virtualenv zipp"

- name: create virtual env && install tablesnap
  command: "{{ item }}"
  with_items:
    - "virtualenv -p python2 {{ tools_install_folder }}/venv/python2-tablesnap"
    - "{{ tools_install_folder }}/venv/python2-tablesnap/bin/pip install tablesnap"

- name: install systemd tablesnap.service unit
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    mode: 0644
  with_items:
    - tablesnap.service

- name: enable and start tablesnap systemd service
  systemd:
    name: tablesnap.service
    daemon_reload: yes
    enabled: true
    state: started
