cassandra_exporter_agent_url: https://github.com/instaclustr/cassandra-exporter/releases/download/v0.9.10/cassandra-exporter-agent-0.9.10.jar
cassandra_exporter_url: https://github.com/criteo/cassandra_exporter/releases/download/2.3.2/cassandra_exporter-2.3.2-all.jar

node_exporter_url: https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-amd64.tar.gz
node_exporter_checksum: "sha256:b2503fd932f85f4e5baf161268854bf5d22001869b84f00fd2d1f57b51b72424"
node_exporter_arch_file_pattern: "node_exporter*.tar.gz"
node_exporter_unarch_folder_pattern: "node_exporter*"
